### ISSUE TITLE
Programs that used to, now won't start with System-Wide Installation

### ISSUE THREAD

**Issue by Pete-McDonald** [briankendall/devreorder#39]
Hi Brian,

Love your software it's a lifesaver.

Running Windows 10 x64

Recently, a few applications have stopped working with the system wide install that used to work just fine.  These include

PCSX2 - Playstation 2 Emulator - The application was unable to start correctly (0xc000007b).
BlissBox API Tool - (I forget the error, and appreciate this is niché software - can get you the error if you need)

For both of these, replacing the dinput8.dll with dinput8org.dll restores functionality.

There has been a recent windows update... I'm not sure if that might have caused something?

Pete

**Comment by briankendall** [comment]
Could you let me know which version of Windows 10 you're running by [following these directions](https://support.microsoft.com/en-us/windows/see-which-version-of-windows-10-you-have-12d35019-4da9-0cb1-ba47-f8b031b712ad)? Let me know both the version number and OS build.

**Comment by Pete-McDonald** [comment]
Thanks for the quick response Brian, of course:

Version: 2004
OS Build: 19041.867

**Comment by Pete-McDonald** [comment]
Also found that TeknoParrot is broken (I'm not sure if you use any of these apps)

![TP_Error](https://user-images.githubusercontent.com/82280111/114301212-c6cfc880-9abb-11eb-9acc-023d91f1f80e.PNG)

**Comment by briankendall** [comment]
I've been trying to see if I can reproduce your issue on my own Windows 10 system, which I just updated to version 20H2, so newer than 2004. So far I can run pcsx2 and TeknoParrot just fine while devreorder is installed system wide.

I'm not sure what the issue is, but my best guess is that something got messed up about your DirectX on your system. This is a bit of a shot in the dark, but maybe try reinstalling DirectX 9.0c from [this link](https://www.microsoft.com/en-us/download/details.aspx?id=8109) and then reinstall devreorder, if necessary. You can check whether the copy of dinput8.dll in your Windows direct is from devreorder or Microsoft by right-clicking it, picking properties, and then looking at its details. If it's by Microsoft then it's the original DLL.

**Comment by Pete-McDonald** [comment]
Argh Brian you're a genius!  That fixed it.  Thank you  so much!

Can you drop your paypal so I can send you something, both for the time and your program? :)

**Comment by briankendall** [comment]
Great, glad to hear that worked out! Every now and then a shot in the dark hits its target.

And yes, donations are not necessary but always appreciated. 😄 My PayPal is brian (at) briankendall (dot) net.

**Comment by mchenier** [comment]
For anyone with that problem, I had the same issue and was never able to make TeknoParrot work with devreorder. I had to place the original dinput8.dll in all the locations where TeknoParrot uses the x86 executable. This means placing it in the TeknoParrot directory, the OpenParrot x86 directory, and also in the game directories that are using OpenParrot x86.
