### ISSUE TITLE
Problem with unicode characters in device names

### ISSUE THREAD

**Issue by TestItOnlyOnce** [briankendall/devreorder#9]
For example `dxdiag` tells that my first two devices are:
```
    Мышь
    Клавиатура
```
But after using your dll there are only blanks there.

**Comment by briankendall** [comment]
@TestItOnlyOnce There is probably a bug in devreorder when devices have non-ASCII names. I'm not offhandedly sure how to fix that exact bug, but I may look into it at some point.

However, try [release 1.0.2](https://github.com/briankendall/devreorder/releases/tag/v1.0.2). It may allow you top work around this problem because it lets you specify devices by their GUID instead of by name. I'd recommend giving that a try, and please let me know if it helps.
